//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarEyeClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// 当前连接的服务器IP地址
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("当前连接的服务器IP地址")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39.108.246.45")]
        public string SvrIp {
            get {
                return ((string)(this["SvrIp"]));
            }
            set {
                this["SvrIp"] = value;
            }
        }
        
        /// <summary>
        /// 当前连接服务器的端口号
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("当前连接服务器的端口号")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("801")]
        public ushort SvrPort {
            get {
                return ((ushort)(this["SvrPort"]));
            }
            set {
                this["SvrPort"] = value;
            }
        }
        
        /// <summary>
        /// 视频服务器IP地址
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("视频服务器IP地址")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120.76.235.109")]
        public string DVRSvrIp {
            get {
                return ((string)(this["DVRSvrIp"]));
            }
            set {
                this["DVRSvrIp"] = value;
            }
        }
        
        /// <summary>
        /// 视频服务器端口号
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("视频服务器端口号")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10554")]
        public ushort DVRSvrPort {
            get {
                return ((ushort)(this["DVRSvrPort"]));
            }
            set {
                this["DVRSvrPort"] = value;
            }
        }
        
        /// <summary>
        /// 自动上报时间间隔(s)
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("自动上报时间间隔(s)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int AutoReportInterval {
            get {
                return ((int)(this["AutoReportInterval"]));
            }
            set {
                this["AutoReportInterval"] = value;
            }
        }
    }
}
